steps:
  # TODO: I doubt we'll keep both package and release commands. But if we do, we could DRY using build matrix.
  - group: ":mac: macOS"
    steps:
      - label: '"Package" for macOS'
        command: |
          source .buildkite/prepare-macos.sh
          make package-mac
          echo "--- :closed_lock_with_key: Code sign via codesign"
          set -x
          codesign \
            --sign "Developer ID Application: Automattic, Inc. (PZYM8XX95Q)" \
            --options runtime \
            --force \
            --verbose \
            download.app
          set +x
          echo "--- :closed_lock_with_key: Notarize"
          bundle exec fastlane notarize_app
        plugins:
          - automattic/a8c-ci-toolkit#3.7.1
        agents:
          queue: mac
        env:
          IMAGE_ID: xcode-16.1
        notify:
          - github_commit_status:
              context: Package for macOS
        artifact_paths:
          - download.app.zip

      - label: '"Release" for macOS'
        command: |
          source .buildkite/prepare-macos.sh
          make release-mac
        plugins:
          - automattic/a8c-ci-toolkit#3.7.1
        agents:
          queue: mac
        env:
          IMAGE_ID: xcode-16.1
        notify:
          - github_commit_status:
              context: Release for macOS
        artifact_paths:
          - download.app.zip

  # TODO: I doubt we'll keep both package and release commands. But if we do, we could DRY using build matrix.
  - group: ":windows: Windows"
    steps:
      - label: '"Package" for Windows'
        command: |
          .buildkite/prepare-windows.ps1
          make package-windows
        notify:
          - github_commit_status:
              context: Package for Windows
        agents:
          queue: windows
        plugins:
          - automattic/a8c-ci-toolkit#mokagio/windows-utils
        env:
          BUILDKITE_PLUGINS_ALWAYS_CLONE_FRESH: 1
        artifact_paths:
          - download.exe

      - label: '"Release" for Windows'
        command: |
          .buildkite/prepare-windows.ps1
          make release-windows
        notify:
          - github_commit_status:
              context: Release for Windows
        agents:
          queue: windows
        plugins:
          - automattic/a8c-ci-toolkit#mokagio/windows-utils
        env:
          BUILDKITE_PLUGINS_ALWAYS_CLONE_FRESH: 1
        artifact_paths:
          - download.exe
          - download.appx
