steps:
  - label: Hello world
    command: |
      brew install go
      # This should call make fyne internally, and does so on a local machine..
      # make release-mac
      make fyne
      make release-mac
    notify:
      - github_commit_status:
          context: "macOS Build"
    agents:
      queue: mac
    env:
      IMAGE_ID: xcode-16.1
    artifact_paths:
      - fyne-cross/dist/**/*.zip
