steps:
  - label: Build on Windows with `package`
    command: |
      .buildkite/prepare-windows.ps1
      make package-windows
    notify:
      - github_commit_status:
          context: Package on Windows
    agents:
      queue: windows
    plugins:
      - automattic/a8c-ci-toolkit#mokagio/windows-utils
    env:
      BUILDKITE_PLUGINS_ALWAYS_CLONE_FRESH: 1
    artifact_paths:
      - download.exe

  - label: Build on Windows with `release`
    command: |
      .buildkite/prepare-windows.ps1
      make release-windows
    notify:
      - github_commit_status:
          context: Release on Windows
    agents:
      queue: windows
    plugins:
      - automattic/a8c-ci-toolkit#mokagio/windows-utils
    env:
      BUILDKITE_PLUGINS_ALWAYS_CLONE_FRESH: 1
    artifact_paths:
      - download.exe
      - download.appx
