steps:
  - label: Package for macOS on macOS
    command: .buildkite/release-mac.sh
    notify:
      - github_commit_status:
          context: macOS Build on macOS
    agents:
      queue: mac
    env:
      IMAGE_ID: xcode-16.1
    artifact_paths:
      - fyne-cross/dist/**/*.zip

  - label: Package for macOS on default
    command: .buildkite/release-mac-from-default.sh
    notify:
      - github_commit_status:
          context: macOS Build on default
    agents:
      queue: default
    artifact_paths:
      - fyne-cross/dist/**/*.zip

  - label: Package for macOS on windows
    command: .buildkite\release-mac-from-windows.ps1
    notify:
      - github_commit_status:
          context: macOS Build on Windows
    agents:
      queue: default
    artifact_paths:
      - fyne-cross\dist\**\*.zip
