steps:
  # TODO: I doubt we'll keep both package and release commands. But if we do, we could DRY using build matrix.
  - group: ':mac: macOS'
    steps:
      - label: '"Package" for macOS'
        command: |
          source .buildkite/prepare-macos.sh
          make package-mac
        plugins:
          - automattic/a8c-ci-toolkit#3.7.1
        agents:
          queue: mac
        env:
          IMAGE_ID: xcode-16.1
        notify:
          - github_commit_status:
              context: Package for macOS
        artifact_paths:
          - download.app.zip

      - label: '"Release" for macOS'
        command: |
          source .buildkite/prepare-macos.sh
          make release-mac
        plugins:
          - automattic/a8c-ci-toolkit#3.7.1
        agents:
          queue: mac
        env:
          IMAGE_ID: xcode-16.1
        notify:
          - github_commit_status:
              context: Release for macOS
        artifact_paths:
          - download.app.zip
